#ifndef UNCLE_RENDERER_PIPELINE_KEY_SHARED_H
#define UNCLE_RENDERER_PIPELINE_KEY_SHARED_H

#define RENDER_PIPELINE_KEY_SKINNING_BIT 8u
#define RENDER_PIPELINE_KEY_DOUBLE_SIDED_BIT 9u
#define RENDER_PIPELINE_KEY_ALPHA_MASK_BIT 4u
#define RENDER_PIPELINE_KEY_ALPHA_MASK_MASK (1u << RENDER_PIPELINE_KEY_ALPHA_MASK_BIT)
#define RENDER_PIPELINE_KEY_DOUBLE_SIDED_MASK (1u << RENDER_PIPELINE_KEY_DOUBLE_SIDED_BIT)

#endif // UNCLE_RENDERER_PIPELINE_KEY_SHARED_H
